### ISSUE TITLE
Invalid token shouldn't crash the server

### ISSUE THREAD

**Issue by gene-pavlovsky** [kevinresol/jsonwebtoken#1]
I've implemented a tink_web server with session using this library. During testing I've made the token invalid on purpose (just added a random character in the front), this crashed the server with this exception:
```
SyntaxError: Unexpected token Ŭ in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.jsonwebtoken_Codec.decodeSegment (C:\project\nextgen\modelclips-2257\mc-2257-db\bin\server\ingest.js:1894:14)
    at jsonwebtoken_verifier_BasicVerifier.verify (C:\project\nextgen\modelclips-2257\mc-2257-db\bin\server\ingest.js:1682:36)
    at Function.ingest_auth_Session.verify (C:\project\nextgen\modelclips-2257\mc-2257-db\bin\server\ingest.js:1727:38)
    at ingest_auth_Session.getUser (C:\project\nextgen\modelclips-2257\mc-2257-db\bin\server\ingest.js:1737:34)
```

It would be nice if it would instead return a proper Failure instead of throwing.

**Comment by kevinresol** [comment]
Posting a reproducible snippet would be helpful. Thanks

**Comment by kevinresol** [comment]
Added a patch, see if that helps?

**Comment by gene-pavlovsky** [comment]
I will be able to test this during the week. I will let you know, and add a snippet (although it's basically almost the same code as in your README).

**Comment by cambiata** [comment]
Stumbled on this one - the patch works for me!

**Comment by gene-pavlovsky** [comment]
Let's merge it then. I totally forgot about this...
